-- ============================================================================
-- RegIntel Copilot: 01_roles_and_database.sql
-- Creates database, schemas, roles, and least-privilege grants.
-- Requires ACCOUNTADMIN or SECURITYADMIN for role creation.
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- -------------------------------------------------------
-- 1. Create project roles (least-privilege hierarchy)
-- -------------------------------------------------------
CREATE ROLE IF NOT EXISTS REGINTEL_ADMIN
    COMMENT = 'RegIntel Copilot: full admin over project database';
CREATE ROLE IF NOT EXISTS REGINTEL_ENGINEER
    COMMENT = 'RegIntel Copilot: data engineering – DDL, ETL, synthetic data';
CREATE ROLE IF NOT EXISTS REGINTEL_ANALYST
    COMMENT = 'RegIntel Copilot: investigation, evidence review, draft findings';
CREATE ROLE IF NOT EXISTS REGINTEL_COMPLIANCE_REVIEWER
    COMMENT = 'RegIntel Copilot: approve/reject findings and reports';
CREATE ROLE IF NOT EXISTS REGINTEL_EXECUTIVE_VIEWER
    COMMENT = 'RegIntel Copilot: read-only dashboards and approved reports';
CREATE ROLE IF NOT EXISTS REGINTEL_APP_ROLE
    COMMENT = 'RegIntel Copilot: Streamlit application service role';

-- Role hierarchy: ADMIN -> ENGINEER -> ANALYST -> VIEWER
GRANT ROLE REGINTEL_ENGINEER           TO ROLE REGINTEL_ADMIN;
GRANT ROLE REGINTEL_ANALYST            TO ROLE REGINTEL_ENGINEER;
GRANT ROLE REGINTEL_COMPLIANCE_REVIEWER TO ROLE REGINTEL_ADMIN;
GRANT ROLE REGINTEL_EXECUTIVE_VIEWER   TO ROLE REGINTEL_ANALYST;
GRANT ROLE REGINTEL_EXECUTIVE_VIEWER   TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT ROLE REGINTEL_APP_ROLE           TO ROLE REGINTEL_ADMIN;

-- Grant admin role to current user
GRANT ROLE REGINTEL_ADMIN TO ROLE ACCOUNTADMIN;

-- -------------------------------------------------------
-- 2. Create database and warehouse grants
-- -------------------------------------------------------
CREATE DATABASE IF NOT EXISTS REGINTEL
    COMMENT = 'RegIntel Copilot: Risk, Fraud and Regulatory Intelligence hackathon project';

GRANT OWNERSHIP ON DATABASE REGINTEL TO ROLE REGINTEL_ADMIN COPY CURRENT GRANTS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REGINTEL_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REGINTEL_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REGINTEL_EXECUTIVE_VIEWER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REGINTEL_APP_ROLE;

-- -------------------------------------------------------
-- 3. Create schemas
-- -------------------------------------------------------
USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Raw synthetic banking data: customers, accounts, transactions';
CREATE SCHEMA IF NOT EXISTS CURATED
    COMMENT = 'Curated views masking sensitive attributes for business users';
CREATE SCHEMA IF NOT EXISTS POLICY
    COMMENT = 'Policy documents, chunks, and search infrastructure';
CREATE SCHEMA IF NOT EXISTS RISK
    COMMENT = 'Risk features, rules, alerts, and evidence';
CREATE SCHEMA IF NOT EXISTS CASE_MGMT
    COMMENT = 'Case lifecycle, findings, and review workflow';
CREATE SCHEMA IF NOT EXISTS AUDIT
    COMMENT = 'Activity logging and audit trail';
CREATE SCHEMA IF NOT EXISTS APP
    COMMENT = 'Application objects: Streamlit, procedures, query templates';

-- -------------------------------------------------------
-- 4. Schema-level grants
-- -------------------------------------------------------

-- ENGINEER: full on RAW, RISK, POLICY
GRANT ALL PRIVILEGES ON SCHEMA RAW       TO ROLE REGINTEL_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RISK      TO ROLE REGINTEL_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA POLICY    TO ROLE REGINTEL_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA CASE_MGMT TO ROLE REGINTEL_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA AUDIT     TO ROLE REGINTEL_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA CURATED   TO ROLE REGINTEL_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA APP       TO ROLE REGINTEL_ENGINEER;

-- ANALYST: usage on curated, risk, case_mgmt, policy, audit, app
GRANT USAGE ON SCHEMA CURATED   TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON SCHEMA RISK      TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON SCHEMA CASE_MGMT TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON SCHEMA POLICY    TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON SCHEMA AUDIT     TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON SCHEMA APP       TO ROLE REGINTEL_ANALYST;

-- COMPLIANCE_REVIEWER: usage on curated, risk, case_mgmt, policy, audit
GRANT USAGE ON SCHEMA CURATED   TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT USAGE ON SCHEMA RISK      TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT USAGE ON SCHEMA CASE_MGMT TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT USAGE ON SCHEMA POLICY    TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT USAGE ON SCHEMA AUDIT     TO ROLE REGINTEL_COMPLIANCE_REVIEWER;

-- EXECUTIVE_VIEWER: usage on curated, risk (alerts only), audit
GRANT USAGE ON SCHEMA CURATED TO ROLE REGINTEL_EXECUTIVE_VIEWER;
GRANT USAGE ON SCHEMA RISK    TO ROLE REGINTEL_EXECUTIVE_VIEWER;
GRANT USAGE ON SCHEMA AUDIT   TO ROLE REGINTEL_EXECUTIVE_VIEWER;

-- APP_ROLE: usage on all schemas for Streamlit
GRANT USAGE ON SCHEMA RAW       TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON SCHEMA CURATED   TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON SCHEMA RISK      TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON SCHEMA CASE_MGMT TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON SCHEMA POLICY    TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON SCHEMA AUDIT     TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON SCHEMA APP       TO ROLE REGINTEL_APP_ROLE;

-- Database-level usage for all roles
GRANT USAGE ON DATABASE REGINTEL TO ROLE REGINTEL_ENGINEER;
GRANT USAGE ON DATABASE REGINTEL TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON DATABASE REGINTEL TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT USAGE ON DATABASE REGINTEL TO ROLE REGINTEL_EXECUTIVE_VIEWER;
GRANT USAGE ON DATABASE REGINTEL TO ROLE REGINTEL_APP_ROLE;

-- Future grants so new tables/views are auto-accessible
GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA CURATED TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RISK    TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RISK    TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED TO ROLE REGINTEL_EXECUTIVE_VIEWER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA CURATED TO ROLE REGINTEL_EXECUTIVE_VIEWER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RISK    TO ROLE REGINTEL_EXECUTIVE_VIEWER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED   TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA CURATED   TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RISK      TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RISK      TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASE_MGMT TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA CASE_MGMT TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA POLICY    TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA POLICY    TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUDIT     TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA AUDIT     TO ROLE REGINTEL_APP_ROLE;
