-- ============================================================================
-- RegIntel Copilot: 02_core_tables.sql
-- Core domain model: banking tables, risk objects, case management, audit.
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- -------------------------------------------------------
-- RAW schema: synthetic banking data
-- -------------------------------------------------------

CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS (
    CUSTOMER_ID          VARCHAR(20)   NOT NULL,
    CUSTOMER_TYPE        VARCHAR(20)   NOT NULL,  -- INDIVIDUAL, CORPORATE, NBFC_BORROWER
    RISK_RATING          VARCHAR(10)   NOT NULL,  -- LOW, MEDIUM, HIGH
    KYC_STATUS           VARCHAR(20)   NOT NULL,  -- VERIFIED, PENDING, EXPIRED
    COUNTRY_CODE         VARCHAR(3)    NOT NULL,
    OCCUPATION_CATEGORY  VARCHAR(50),
    EXPECTED_MONTHLY_TURNOVER NUMBER(18,2),
    ONBOARDING_DATE      DATE          NOT NULL,
    IS_PEP               BOOLEAN       DEFAULT FALSE,
    RECORD_CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
) COMMENT = 'Synthetic customer master. No real PII.';

CREATE TABLE IF NOT EXISTS RAW.ACCOUNTS (
    ACCOUNT_ID         VARCHAR(20)    NOT NULL,
    CUSTOMER_ID        VARCHAR(20)    NOT NULL,
    ACCOUNT_TYPE       VARCHAR(20)    NOT NULL,  -- SAVINGS, CURRENT, CREDIT, LOAN
    CURRENCY_CODE      VARCHAR(3)     DEFAULT 'INR',
    ACCOUNT_STATUS     VARCHAR(15)    NOT NULL,  -- ACTIVE, DORMANT, CLOSED, FROZEN
    OPEN_DATE          DATE           NOT NULL,
    HOME_BRANCH_CODE   VARCHAR(10),
    CURRENT_BALANCE    NUMBER(18,2)   DEFAULT 0,
    CREDIT_LIMIT       NUMBER(18,2),
    RECORD_CREATED_AT  TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID)
) COMMENT = 'Synthetic bank accounts linked to customers.';

CREATE TABLE IF NOT EXISTS RAW.TRANSACTIONS (
    TRANSACTION_ID          VARCHAR(30)    NOT NULL,
    ACCOUNT_ID              VARCHAR(20)    NOT NULL,
    COUNTERPARTY_ACCOUNT_ID VARCHAR(20),
    TRANSACTION_TIMESTAMP   TIMESTAMP_NTZ  NOT NULL,
    TRANSACTION_TYPE        VARCHAR(15)    NOT NULL,  -- CREDIT, DEBIT, TRANSFER_IN, TRANSFER_OUT
    CHANNEL                 VARCHAR(15),              -- BRANCH, ATM, ONLINE, MOBILE, WIRE
    AMOUNT                  NUMBER(18,2)   NOT NULL,
    CURRENCY_CODE           VARCHAR(3)     DEFAULT 'INR',
    ORIGIN_COUNTRY_CODE     VARCHAR(3),
    DESTINATION_COUNTRY_CODE VARCHAR(3),
    MERCHANT_CATEGORY       VARCHAR(50),
    DEVICE_ID               VARCHAR(64),   -- Synthetic device fingerprint hash
    IP_ADDRESS_TOKEN        VARCHAR(64),   -- Tokenized, not real IP
    TRANSACTION_STATUS      VARCHAR(15)    DEFAULT 'COMPLETED',
    DESCRIPTION             VARCHAR(200),
    RECORD_CREATED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID)
) COMMENT = 'Synthetic transaction ledger. All IDs are fictitious.';

CREATE TABLE IF NOT EXISTS RAW.ACCOUNT_DAILY_BALANCE (
    ACCOUNT_ID          VARCHAR(20)    NOT NULL,
    BALANCE_DATE        DATE           NOT NULL,
    OPENING_BALANCE     NUMBER(18,2)   NOT NULL,
    TOTAL_CREDITS       NUMBER(18,2)   DEFAULT 0,
    TOTAL_DEBITS        NUMBER(18,2)   DEFAULT 0,
    CLOSING_BALANCE     NUMBER(18,2)   NOT NULL,
    AVAILABLE_LIQUIDITY NUMBER(18,2),
    CONSTRAINT PK_DAILY_BALANCE PRIMARY KEY (ACCOUNT_ID, BALANCE_DATE)
) COMMENT = 'Daily balance snapshots for liquidity analysis.';

-- -------------------------------------------------------
-- RISK schema: rules, alerts, evidence
-- -------------------------------------------------------

CREATE TABLE IF NOT EXISTS RISK.RISK_RULES (
    RULE_ID          VARCHAR(20)   NOT NULL,
    RULE_NAME        VARCHAR(100)  NOT NULL,
    RISK_DOMAIN      VARCHAR(20)   NOT NULL,  -- AML, FRAUD, CREDIT, LIQUIDITY
    RULE_DESCRIPTION VARCHAR(500),
    RULE_VERSION     INTEGER       NOT NULL DEFAULT 1,
    SEVERITY         VARCHAR(10)   NOT NULL,  -- LOW, MEDIUM, HIGH, CRITICAL
    THRESHOLD_CONFIG VARIANT       NOT NULL,  -- JSON with threshold parameters
    EFFECTIVE_FROM   DATE          NOT NULL,
    EFFECTIVE_TO     DATE,
    ACTIVE_FLAG      BOOLEAN       DEFAULT TRUE,
    POLICY_REFERENCE VARCHAR(50),  -- Maps to policy document section
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_RISK_RULES PRIMARY KEY (RULE_ID, RULE_VERSION)
) COMMENT = 'Versioned risk rules with configurable thresholds. Demo values only.';

CREATE TABLE IF NOT EXISTS RISK.ALERTS (
    ALERT_ID               VARCHAR(30)    NOT NULL,
    ALERT_TIMESTAMP        TIMESTAMP_NTZ  NOT NULL,
    CUSTOMER_ID            VARCHAR(20)    NOT NULL,
    ACCOUNT_ID             VARCHAR(20)    NOT NULL,
    PRIMARY_TRANSACTION_ID VARCHAR(30),
    RULE_ID                VARCHAR(20)    NOT NULL,
    RULE_VERSION           INTEGER        NOT NULL,
    RISK_SCORE             NUMBER(5,2)    NOT NULL,
    SEVERITY               VARCHAR(10)    NOT NULL,
    ALERT_STATUS           VARCHAR(20)    DEFAULT 'NEW',  -- NEW, UNDER_REVIEW, ESCALATED, CLOSED_TRUE_POS, CLOSED_FALSE_POS
    EXPLANATION            VARCHAR(1000)  NOT NULL,
    EVIDENCE_SNAPSHOT_ID   VARCHAR(30),
    RECORD_CREATED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ALERTS PRIMARY KEY (ALERT_ID)
) COMMENT = 'Risk alerts generated by deterministic rules.';

CREATE TABLE IF NOT EXISTS RISK.ALERT_EVIDENCE (
    EVIDENCE_ID        VARCHAR(30)    NOT NULL,
    ALERT_ID           VARCHAR(30)    NOT NULL,
    EVIDENCE_TYPE      VARCHAR(30)    NOT NULL,  -- TRANSACTION, BALANCE, RULE_EVAL, CUSTOMER_PROFILE
    SOURCE_OBJECT      VARCHAR(100)   NOT NULL,
    SOURCE_RECORD_ID   VARCHAR(30)    NOT NULL,
    EVIDENCE_TIMESTAMP TIMESTAMP_NTZ  NOT NULL,
    EVIDENCE_JSON      VARIANT        NOT NULL,
    HASH_VALUE         VARCHAR(64)    NOT NULL,  -- SHA-256 for integrity verification
    CREATED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ALERT_EVIDENCE PRIMARY KEY (EVIDENCE_ID)
) COMMENT = 'Immutable evidence snapshots linked to alerts.';

-- -------------------------------------------------------
-- CASE_MGMT schema: case lifecycle and findings
-- -------------------------------------------------------

CREATE TABLE IF NOT EXISTS CASE_MGMT.CASES (
    CASE_ID           VARCHAR(20)    NOT NULL,
    ALERT_ID          VARCHAR(30)    NOT NULL,
    CASE_STATUS       VARCHAR(20)    NOT NULL DEFAULT 'NEW',
    ASSIGNED_ROLE     VARCHAR(50),
    CREATED_BY        VARCHAR(100)   NOT NULL,
    CREATED_AT        TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    REVIEWED_BY       VARCHAR(100),
    REVIEWED_AT       TIMESTAMP_NTZ,
    DISPOSITION       VARCHAR(50),   -- SUSPICIOUS, NOT_SUSPICIOUS, ESCALATED, INSUFFICIENT_EVIDENCE
    REVIEWER_COMMENTS VARCHAR(2000),
    CONSTRAINT PK_CASES PRIMARY KEY (CASE_ID)
) COMMENT = 'Investigation cases linked to alerts.';

CREATE TABLE IF NOT EXISTS CASE_MGMT.FINDINGS (
    FINDING_ID               VARCHAR(30)    NOT NULL,
    CASE_ID                  VARCHAR(20)    NOT NULL,
    FINDING_VERSION          INTEGER        NOT NULL DEFAULT 1,
    FINDING_STATUS           VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    NARRATIVE                VARCHAR(5000),
    SUPPORTING_EVIDENCE_JSON VARIANT,
    POLICY_CITATIONS_JSON    VARIANT,
    CREATED_BY               VARCHAR(100)   NOT NULL,
    CREATED_AT               TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    APPROVED_BY              VARCHAR(100),
    APPROVED_AT              TIMESTAMP_NTZ,
    CONSTRAINT PK_FINDINGS PRIMARY KEY (FINDING_ID, FINDING_VERSION)
) COMMENT = 'Versioned, immutable findings. DRAFT until human approval.';

CREATE TABLE IF NOT EXISTS CASE_MGMT.CASE_EVIDENCE (
    CASE_ID        VARCHAR(20)    NOT NULL,
    EVIDENCE_ID    VARCHAR(30)    NOT NULL,
    ATTACHED_BY    VARCHAR(100)   NOT NULL,
    ATTACHED_AT    TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CASE_EVIDENCE PRIMARY KEY (CASE_ID, EVIDENCE_ID)
) COMMENT = 'Links cases to their evidence records.';

-- -------------------------------------------------------
-- AUDIT schema: activity log
-- -------------------------------------------------------

CREATE TABLE IF NOT EXISTS AUDIT.ACTIVITY_LOG (
    ACTIVITY_ID      VARCHAR(36)    NOT NULL,  -- UUID
    EVENT_TIMESTAMP  TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    USER_NAME        VARCHAR(100),
    ACTIVE_ROLE      VARCHAR(100),
    SESSION_ID       VARCHAR(100),
    ACTION_TYPE      VARCHAR(50)    NOT NULL,
    OBJECT_TYPE      VARCHAR(50),
    OBJECT_ID        VARCHAR(50),
    REQUEST_TEXT     VARCHAR(4000),
    RESPONSE_SUMMARY VARCHAR(2000),
    QUERY_ID         VARCHAR(100),
    STATUS           VARCHAR(20)    DEFAULT 'SUCCESS',
    ERROR_MESSAGE    VARCHAR(2000),
    CONSTRAINT PK_ACTIVITY_LOG PRIMARY KEY (ACTIVITY_ID)
) COMMENT = 'Audit trail for all copilot actions. Immutable.';

-- -------------------------------------------------------
-- POLICY schema: policy chunks for search
-- -------------------------------------------------------

CREATE TABLE IF NOT EXISTS POLICY.POLICY_DOCUMENTS (
    POLICY_ID      VARCHAR(20)    NOT NULL,
    POLICY_VERSION INTEGER        NOT NULL DEFAULT 1,
    POLICY_NAME    VARCHAR(200)   NOT NULL,
    EFFECTIVE_DATE DATE           NOT NULL,
    SOURCE_FILENAME VARCHAR(100)  NOT NULL,
    FULL_TEXT      VARCHAR(16777216),
    CREATED_AT     TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_POLICY_DOCS PRIMARY KEY (POLICY_ID, POLICY_VERSION)
) COMMENT = 'Synthetic policy documents for demo. NOT legal advice.';

CREATE TABLE IF NOT EXISTS POLICY.POLICY_CHUNKS (
    CHUNK_ID        VARCHAR(30)    NOT NULL,
    POLICY_ID       VARCHAR(20)    NOT NULL,
    POLICY_VERSION  INTEGER        NOT NULL,
    SECTION_ID      VARCHAR(20)    NOT NULL,
    PARAGRAPH_ID    VARCHAR(20)    NOT NULL,
    SOURCE_FILENAME VARCHAR(100)   NOT NULL,
    CHUNK_TEXT      VARCHAR(4000)  NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_POLICY_CHUNKS PRIMARY KEY (CHUNK_ID)
) COMMENT = 'Chunked policy text for keyword search retrieval.';

-- -------------------------------------------------------
-- RAW schema: hidden test validation table
-- -------------------------------------------------------

CREATE TABLE IF NOT EXISTS RAW.SCENARIO_VALIDATION (
    SCENARIO_ID       VARCHAR(20)   NOT NULL,
    SCENARIO_TYPE     VARCHAR(50)   NOT NULL,
    EXPECTED_RULE_ID  VARCHAR(20)   NOT NULL,
    ACCOUNT_ID        VARCHAR(20)   NOT NULL,
    DESCRIPTION       VARCHAR(500),
    CONSTRAINT PK_SCENARIO_VAL PRIMARY KEY (SCENARIO_ID)
) COMMENT = 'Hidden planted scenario table for testing precision/recall. Not exposed to app.';

-- -------------------------------------------------------
-- CURATED schema: safe views for business users
-- -------------------------------------------------------

CREATE OR REPLACE VIEW CURATED.V_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_TYPE,
    RISK_RATING,
    KYC_STATUS,
    COUNTRY_CODE,
    OCCUPATION_CATEGORY,
    EXPECTED_MONTHLY_TURNOVER,
    ONBOARDING_DATE,
    IS_PEP
FROM RAW.CUSTOMERS
COMMENT = 'Curated customer view - no internal record timestamps exposed.';

CREATE OR REPLACE VIEW CURATED.V_ACCOUNTS AS
SELECT
    A.ACCOUNT_ID,
    A.CUSTOMER_ID,
    A.ACCOUNT_TYPE,
    A.CURRENCY_CODE,
    A.ACCOUNT_STATUS,
    A.OPEN_DATE,
    A.HOME_BRANCH_CODE,
    A.CURRENT_BALANCE,
    A.CREDIT_LIMIT
FROM RAW.ACCOUNTS A
COMMENT = 'Curated account view for business users.';

CREATE OR REPLACE VIEW CURATED.V_TRANSACTIONS AS
SELECT
    T.TRANSACTION_ID,
    T.ACCOUNT_ID,
    T.COUNTERPARTY_ACCOUNT_ID,
    T.TRANSACTION_TIMESTAMP,
    T.TRANSACTION_TYPE,
    T.CHANNEL,
    T.AMOUNT,
    T.CURRENCY_CODE,
    T.ORIGIN_COUNTRY_CODE,
    T.DESTINATION_COUNTRY_CODE,
    T.MERCHANT_CATEGORY,
    T.TRANSACTION_STATUS,
    T.DESCRIPTION
FROM RAW.TRANSACTIONS T
COMMENT = 'Curated transaction view - device/IP tokens excluded.';

CREATE OR REPLACE VIEW CURATED.V_DAILY_BALANCE AS
SELECT
    ACCOUNT_ID,
    BALANCE_DATE,
    OPENING_BALANCE,
    TOTAL_CREDITS,
    TOTAL_DEBITS,
    CLOSING_BALANCE,
    AVAILABLE_LIQUIDITY
FROM RAW.ACCOUNT_DAILY_BALANCE
COMMENT = 'Daily balance view for liquidity analysis.';

-- Grant SELECT on existing views to roles
GRANT SELECT ON ALL VIEWS IN SCHEMA CURATED TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA CURATED TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA CURATED TO ROLE REGINTEL_EXECUTIVE_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA CURATED TO ROLE REGINTEL_APP_ROLE;

-- Grant SELECT on RISK and CASE_MGMT tables
GRANT SELECT ON ALL TABLES IN SCHEMA RISK TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RISK TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CASE_MGMT TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CASE_MGMT TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CASE_MGMT TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA POLICY TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA POLICY TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AUDIT TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA AUDIT TO ROLE REGINTEL_APP_ROLE;
