-- ============================================================================
-- RegIntel Copilot: 04_data_quality.sql
-- Data quality validation for synthetic data.
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- 1. Row counts
SELECT 'CUSTOMERS' AS TBL, COUNT(*) AS CNT, 500 AS EXPECTED FROM RAW.CUSTOMERS
UNION ALL SELECT 'ACCOUNTS', COUNT(*), 700 FROM RAW.ACCOUNTS
UNION ALL SELECT 'TRANSACTIONS', COUNT(*), 45000 FROM RAW.TRANSACTIONS
UNION ALL SELECT 'DAILY_BALANCE', COUNT(*), 50000 FROM RAW.ACCOUNT_DAILY_BALANCE
UNION ALL SELECT 'SCENARIOS', COUNT(*), 10 FROM RAW.SCENARIO_VALIDATION;

-- 2. Primary key uniqueness
SELECT 'CUSTOMERS_PK' AS CHECK_NAME, COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) AS DUPLICATES FROM RAW.CUSTOMERS
UNION ALL SELECT 'ACCOUNTS_PK', COUNT(*) - COUNT(DISTINCT ACCOUNT_ID) FROM RAW.ACCOUNTS
UNION ALL SELECT 'TRANSACTIONS_PK', COUNT(*) - COUNT(DISTINCT TRANSACTION_ID) FROM RAW.TRANSACTIONS;

-- 3. Referential integrity: accounts -> customers
SELECT 'ORPHAN_ACCOUNTS' AS CHECK_NAME, COUNT(*) AS CNT
FROM RAW.ACCOUNTS A
LEFT JOIN RAW.CUSTOMERS C ON A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

-- 4. Null checks on required fields
SELECT 'NULL_CUSTOMER_ID' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW.CUSTOMERS WHERE CUSTOMER_ID IS NULL
UNION ALL SELECT 'NULL_ACCOUNT_ID', COUNT(*) FROM RAW.ACCOUNTS WHERE ACCOUNT_ID IS NULL
UNION ALL SELECT 'NULL_TXN_ID', COUNT(*) FROM RAW.TRANSACTIONS WHERE TRANSACTION_ID IS NULL
UNION ALL SELECT 'NULL_TXN_AMOUNT', COUNT(*) FROM RAW.TRANSACTIONS WHERE AMOUNT IS NULL
UNION ALL SELECT 'NULL_TXN_TIMESTAMP', COUNT(*) FROM RAW.TRANSACTIONS WHERE TRANSACTION_TIMESTAMP IS NULL;

-- 5. Valid enum values
SELECT 'INVALID_ACCT_STATUS' AS CHECK_NAME, COUNT(*) AS CNT
FROM RAW.ACCOUNTS WHERE ACCOUNT_STATUS NOT IN ('ACTIVE','DORMANT','CLOSED','FROZEN');

SELECT 'INVALID_TXN_TYPE' AS CHECK_NAME, COUNT(*) AS CNT
FROM RAW.TRANSACTIONS WHERE TRANSACTION_TYPE NOT IN ('CREDIT','DEBIT','TRANSFER_IN','TRANSFER_OUT');

-- 6. Verify pinned demo IDs exist
SELECT 'A000123_EXISTS' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW.ACCOUNTS WHERE ACCOUNT_ID = 'A000123'
UNION ALL SELECT 'C000017_EXISTS', COUNT(*) FROM RAW.CUSTOMERS WHERE CUSTOMER_ID = 'C000017';

-- 7. Amount validity (no negatives)
SELECT 'NEGATIVE_AMOUNTS' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW.TRANSACTIONS WHERE AMOUNT < 0;

-- 8. Balance date range
SELECT MIN(BALANCE_DATE) AS MIN_DATE, MAX(BALANCE_DATE) AS MAX_DATE FROM RAW.ACCOUNT_DAILY_BALANCE;
