-- ============================================================================
-- RegIntel Copilot: 05_risk_features.sql
-- Deterministic, explainable risk feature views.
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- F1: Transaction amount vs expected monthly turnover
CREATE OR REPLACE VIEW RISK.V_FEAT_AMOUNT_VS_TURNOVER AS
SELECT
    T.TRANSACTION_ID, T.ACCOUNT_ID, T.AMOUNT, T.TRANSACTION_TIMESTAMP,
    A.CUSTOMER_ID, C.EXPECTED_MONTHLY_TURNOVER,
    CASE WHEN C.EXPECTED_MONTHLY_TURNOVER > 0
         THEN ROUND(T.AMOUNT / C.EXPECTED_MONTHLY_TURNOVER * 100, 2)
         ELSE NULL END AS PCT_OF_MONTHLY_TURNOVER
FROM RAW.TRANSACTIONS T
JOIN RAW.ACCOUNTS A ON T.ACCOUNT_ID = A.ACCOUNT_ID
JOIN RAW.CUSTOMERS C ON A.CUSTOMER_ID = C.CUSTOMER_ID;

-- F2: Rolling 24h transaction count and sum per account
CREATE OR REPLACE VIEW RISK.V_FEAT_ROLLING_24H AS
SELECT
    T.TRANSACTION_ID, T.ACCOUNT_ID, T.TRANSACTION_TIMESTAMP, T.AMOUNT,
    COUNT(*) OVER (PARTITION BY T.ACCOUNT_ID
        ORDER BY T.TRANSACTION_TIMESTAMP
        RANGE BETWEEN INTERVAL '24 HOURS' PRECEDING AND CURRENT ROW) AS TXN_COUNT_24H,
    SUM(T.AMOUNT) OVER (PARTITION BY T.ACCOUNT_ID
        ORDER BY T.TRANSACTION_TIMESTAMP
        RANGE BETWEEN INTERVAL '24 HOURS' PRECEDING AND CURRENT ROW) AS TXN_SUM_24H
FROM RAW.TRANSACTIONS T;

-- F3: Distinct destination countries per account (trailing 30 days)
CREATE OR REPLACE VIEW RISK.V_FEAT_DEST_COUNTRIES AS
SELECT
    ACCOUNT_ID,
    COUNT(DISTINCT DESTINATION_COUNTRY_CODE) AS DISTINCT_DEST_COUNTRIES_30D,
    ARRAY_AGG(DISTINCT DESTINATION_COUNTRY_CODE) AS DEST_COUNTRY_LIST
FROM RAW.TRANSACTIONS
WHERE TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY ACCOUNT_ID;

-- F4: Structuring detection - transactions just below threshold
CREATE OR REPLACE VIEW RISK.V_FEAT_STRUCTURING AS
SELECT
    ACCOUNT_ID,
    COUNT(*) AS TXN_COUNT_NEAR_THRESHOLD,
    SUM(AMOUNT) AS TOTAL_NEAR_THRESHOLD,
    MIN(TRANSACTION_TIMESTAMP) AS FIRST_TXN,
    MAX(TRANSACTION_TIMESTAMP) AS LAST_TXN,
    ARRAY_AGG(TRANSACTION_ID) AS TRANSACTION_IDS
FROM RAW.TRANSACTIONS
WHERE AMOUNT BETWEEN 45000 AND 49999
AND TRANSACTION_TYPE IN ('DEBIT', 'TRANSFER_OUT')
AND TRANSACTION_TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY ACCOUNT_ID
HAVING COUNT(*) >= 3;

-- F5: Rapid fund movement - credits followed by debits within hours
CREATE OR REPLACE VIEW RISK.V_FEAT_RAPID_MOVEMENT AS
SELECT
    C.ACCOUNT_ID,
    C.TRANSACTION_ID AS CREDIT_TXN_ID,
    C.AMOUNT AS CREDIT_AMOUNT,
    C.TRANSACTION_TIMESTAMP AS CREDIT_TIME,
    D.TRANSACTION_ID AS DEBIT_TXN_ID,
    D.AMOUNT AS DEBIT_AMOUNT,
    D.TRANSACTION_TIMESTAMP AS DEBIT_TIME,
    DATEDIFF('minute', C.TRANSACTION_TIMESTAMP, D.TRANSACTION_TIMESTAMP) AS MINUTES_BETWEEN,
    ROUND(D.AMOUNT / NULLIF(C.AMOUNT, 0) * 100, 2) AS PCT_MOVED
FROM RAW.TRANSACTIONS C
JOIN RAW.TRANSACTIONS D
    ON C.ACCOUNT_ID = D.ACCOUNT_ID
    AND D.TRANSACTION_TIMESTAMP > C.TRANSACTION_TIMESTAMP
    AND DATEDIFF('hour', C.TRANSACTION_TIMESTAMP, D.TRANSACTION_TIMESTAMP) <= 24
WHERE C.TRANSACTION_TYPE IN ('CREDIT', 'TRANSFER_IN')
AND D.TRANSACTION_TYPE IN ('DEBIT', 'TRANSFER_OUT')
AND C.AMOUNT >= 100000
AND D.AMOUNT >= 100000;

-- F6: Dormancy analysis
CREATE OR REPLACE VIEW RISK.V_FEAT_DORMANCY AS
SELECT
    A.ACCOUNT_ID,
    A.ACCOUNT_STATUS,
    MAX(T.TRANSACTION_TIMESTAMP) AS LAST_TXN_BEFORE,
    MIN(T2.TRANSACTION_TIMESTAMP) AS FIRST_TXN_AFTER,
    DATEDIFF('day', MAX(T.TRANSACTION_TIMESTAMP), MIN(T2.TRANSACTION_TIMESTAMP)) AS DORMANT_DAYS
FROM RAW.ACCOUNTS A
LEFT JOIN RAW.TRANSACTIONS T ON A.ACCOUNT_ID = T.ACCOUNT_ID
    AND T.TRANSACTION_TIMESTAMP < DATEADD('day', -90, CURRENT_TIMESTAMP())
LEFT JOIN RAW.TRANSACTIONS T2 ON A.ACCOUNT_ID = T2.ACCOUNT_ID
    AND T2.TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_TIMESTAMP())
WHERE A.ACCOUNT_STATUS = 'DORMANT'
GROUP BY A.ACCOUNT_ID, A.ACCOUNT_STATUS
HAVING MIN(T2.TRANSACTION_TIMESTAMP) IS NOT NULL;

-- F7: Credit utilization
CREATE OR REPLACE VIEW RISK.V_FEAT_CREDIT_UTILIZATION AS
SELECT
    A.ACCOUNT_ID, A.CUSTOMER_ID, A.CREDIT_LIMIT, A.CURRENT_BALANCE,
    ROUND(A.CURRENT_BALANCE / NULLIF(A.CREDIT_LIMIT, 0) * 100, 2) AS UTILIZATION_PCT,
    SUM(CASE WHEN T.TRANSACTION_TYPE = 'DEBIT' THEN T.AMOUNT ELSE 0 END) AS TOTAL_DEBITS_30D
FROM RAW.ACCOUNTS A
LEFT JOIN RAW.TRANSACTIONS T ON A.ACCOUNT_ID = T.ACCOUNT_ID
    AND T.TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_TIMESTAMP())
WHERE A.ACCOUNT_TYPE = 'CREDIT' AND A.CREDIT_LIMIT > 0
GROUP BY A.ACCOUNT_ID, A.CUSTOMER_ID, A.CREDIT_LIMIT, A.CURRENT_BALANCE;

-- F8: Liquidity decline
CREATE OR REPLACE VIEW RISK.V_FEAT_LIQUIDITY_DECLINE AS
SELECT
    ACCOUNT_ID, BALANCE_DATE, CLOSING_BALANCE, AVAILABLE_LIQUIDITY,
    LAG(CLOSING_BALANCE, 1) OVER (PARTITION BY ACCOUNT_ID ORDER BY BALANCE_DATE) AS PREV_BALANCE,
    LAG(CLOSING_BALANCE, 7) OVER (PARTITION BY ACCOUNT_ID ORDER BY BALANCE_DATE) AS BALANCE_7D_AGO,
    CASE WHEN LAG(CLOSING_BALANCE, 7) OVER (PARTITION BY ACCOUNT_ID ORDER BY BALANCE_DATE) > 0
         THEN ROUND((CLOSING_BALANCE - LAG(CLOSING_BALANCE, 7) OVER (PARTITION BY ACCOUNT_ID ORDER BY BALANCE_DATE))
              / LAG(CLOSING_BALANCE, 7) OVER (PARTITION BY ACCOUNT_ID ORDER BY BALANCE_DATE) * 100, 2)
         ELSE NULL END AS PCT_CHANGE_7D
FROM RAW.ACCOUNT_DAILY_BALANCE;

-- F9: Mule behavior - multiple unique credit originators then outbound
CREATE OR REPLACE VIEW RISK.V_FEAT_MULE_BEHAVIOR AS
SELECT
    T.ACCOUNT_ID,
    COUNT(DISTINCT CASE WHEN T.TRANSACTION_TYPE IN ('CREDIT','TRANSFER_IN')
                        THEN T.COUNTERPARTY_ACCOUNT_ID END) AS UNIQUE_CREDIT_SOURCES_24H,
    SUM(CASE WHEN T.TRANSACTION_TYPE IN ('CREDIT','TRANSFER_IN') THEN T.AMOUNT ELSE 0 END) AS TOTAL_CREDITS_24H,
    SUM(CASE WHEN T.TRANSACTION_TYPE IN ('DEBIT','TRANSFER_OUT') THEN T.AMOUNT ELSE 0 END) AS TOTAL_DEBITS_24H,
    CASE WHEN SUM(CASE WHEN T.TRANSACTION_TYPE IN ('CREDIT','TRANSFER_IN') THEN T.AMOUNT ELSE 0 END) > 0
         THEN ROUND(SUM(CASE WHEN T.TRANSACTION_TYPE IN ('DEBIT','TRANSFER_OUT') THEN T.AMOUNT ELSE 0 END)
              / SUM(CASE WHEN T.TRANSACTION_TYPE IN ('CREDIT','TRANSFER_IN') THEN T.AMOUNT ELSE 0 END) * 100, 2)
         ELSE 0 END AS PCT_MOVED_OUT,
    MIN(T.TRANSACTION_TIMESTAMP) AS WINDOW_START,
    MAX(T.TRANSACTION_TIMESTAMP) AS WINDOW_END
FROM RAW.TRANSACTIONS T
WHERE T.TRANSACTION_TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY T.ACCOUNT_ID
HAVING COUNT(DISTINCT CASE WHEN T.TRANSACTION_TYPE IN ('CREDIT','TRANSFER_IN')
                           THEN T.COUNTERPARTY_ACCOUNT_ID END) >= 3;
