-- ============================================================================
-- RegIntel Copilot: 07_alert_pipeline.sql
-- Materializes alert candidates into RISK.ALERTS with evidence snapshots.
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- Materialize alerts from candidates (dedup by account+rule)
INSERT INTO RISK.ALERTS (ALERT_ID, ALERT_TIMESTAMP, CUSTOMER_ID, ACCOUNT_ID,
    PRIMARY_TRANSACTION_ID, RULE_ID, RULE_VERSION, RISK_SCORE, SEVERITY,
    ALERT_STATUS, EXPLANATION, EVIDENCE_SNAPSHOT_ID)
SELECT
    'ALT_' || LPAD(ROW_NUMBER() OVER (ORDER BY RISK_SCORE DESC)::VARCHAR, 6, '0') AS ALERT_ID,
    EVAL_TIMESTAMP AS ALERT_TIMESTAMP,
    CUSTOMER_ID, ACCOUNT_ID, PRIMARY_TRANSACTION_ID,
    RULE_ID, RULE_VERSION, RISK_SCORE, SEVERITY,
    'NEW' AS ALERT_STATUS,
    EXPLANATION,
    'ES_' || LPAD(ROW_NUMBER() OVER (ORDER BY RISK_SCORE DESC)::VARCHAR, 6, '0') AS EVIDENCE_SNAPSHOT_ID
FROM RISK.V_ALERT_CANDIDATES
QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID, RULE_ID ORDER BY RISK_SCORE DESC) = 1;

-- Create evidence snapshots for each alert
INSERT INTO RISK.ALERT_EVIDENCE (EVIDENCE_ID, ALERT_ID, EVIDENCE_TYPE, SOURCE_OBJECT,
    SOURCE_RECORD_ID, EVIDENCE_TIMESTAMP, EVIDENCE_JSON, HASH_VALUE)
SELECT
    'EV_' || LPAD(ROW_NUMBER() OVER (ORDER BY A.ALERT_ID)::VARCHAR, 6, '0'),
    A.ALERT_ID,
    'RULE_EVAL',
    'RISK.V_ALERT_CANDIDATES',
    A.ALERT_ID,
    A.ALERT_TIMESTAMP,
    OBJECT_CONSTRUCT(
        'rule_id', A.RULE_ID,
        'rule_version', A.RULE_VERSION,
        'account_id', A.ACCOUNT_ID,
        'customer_id', A.CUSTOMER_ID,
        'risk_score', A.RISK_SCORE,
        'severity', A.SEVERITY,
        'explanation', A.EXPLANATION,
        'primary_transaction_id', A.PRIMARY_TRANSACTION_ID
    ),
    SHA2(A.ALERT_ID || A.RULE_ID || A.ACCOUNT_ID || A.RISK_SCORE::VARCHAR || A.EXPLANATION)
FROM RISK.ALERTS A;

-- Add transaction evidence for alerts with primary transaction
INSERT INTO RISK.ALERT_EVIDENCE (EVIDENCE_ID, ALERT_ID, EVIDENCE_TYPE, SOURCE_OBJECT,
    SOURCE_RECORD_ID, EVIDENCE_TIMESTAMP, EVIDENCE_JSON, HASH_VALUE)
SELECT
    'EV_TXN_' || LPAD(ROW_NUMBER() OVER (ORDER BY A.ALERT_ID)::VARCHAR, 6, '0'),
    A.ALERT_ID,
    'TRANSACTION',
    'RAW.TRANSACTIONS',
    T.TRANSACTION_ID,
    T.TRANSACTION_TIMESTAMP,
    OBJECT_CONSTRUCT(
        'transaction_id', T.TRANSACTION_ID,
        'account_id', T.ACCOUNT_ID,
        'amount', T.AMOUNT,
        'type', T.TRANSACTION_TYPE,
        'channel', T.CHANNEL,
        'timestamp', T.TRANSACTION_TIMESTAMP,
        'origin_country', T.ORIGIN_COUNTRY_CODE,
        'dest_country', T.DESTINATION_COUNTRY_CODE
    ),
    SHA2(T.TRANSACTION_ID || T.AMOUNT::VARCHAR || T.TRANSACTION_TIMESTAMP::VARCHAR)
FROM RISK.ALERTS A
JOIN RAW.TRANSACTIONS T ON A.PRIMARY_TRANSACTION_ID = T.TRANSACTION_ID
WHERE A.PRIMARY_TRANSACTION_ID IS NOT NULL;
