-- ============================================================================
-- RegIntel Copilot: 09_semantic_layer.sql
-- Parameterized query templates and intent routing (no Cortex Analyst).
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- Query templates table for the QA contract
CREATE TABLE IF NOT EXISTS APP.QUERY_TEMPLATES (
    TEMPLATE_ID VARCHAR(30) NOT NULL,
    INTENT VARCHAR(50) NOT NULL,
    KEYWORDS VARCHAR(500) NOT NULL,
    DESCRIPTION VARCHAR(500),
    SQL_TEMPLATE VARCHAR(8000) NOT NULL,
    CONSTRAINT PK_TEMPLATES PRIMARY KEY (TEMPLATE_ID)
);

INSERT INTO APP.QUERY_TEMPLATES (TEMPLATE_ID, INTENT, KEYWORDS, DESCRIPTION, SQL_TEMPLATE)
SELECT 'QT_001', 'ALERT_INVESTIGATION',
    'flagged,alert,risk score,why,account,signal,rule',
    'Investigate a specific account alert with rules and evidence',
    'SELECT A.ALERT_ID, A.RULE_ID, A.RULE_VERSION, A.RISK_SCORE, A.SEVERITY, A.EXPLANATION,
        A.ACCOUNT_ID, A.CUSTOMER_ID, A.PRIMARY_TRANSACTION_ID, A.ALERT_STATUS,
        R.RULE_NAME, R.RISK_DOMAIN, R.THRESHOLD_CONFIG
    FROM RISK.ALERTS A JOIN RISK.RISK_RULES R ON A.RULE_ID = R.RULE_ID AND A.RULE_VERSION = R.RULE_VERSION
    WHERE A.ACCOUNT_ID = :PARAM1 ORDER BY A.RISK_SCORE DESC'
UNION ALL SELECT 'QT_002', 'TOP_ALERTS',
    'highest,top,open,alert,risk,score,contributing',
    'Show open alerts ranked by risk score with contributing rules',
    'SELECT A.ALERT_ID, A.ACCOUNT_ID, A.CUSTOMER_ID, A.RULE_ID, R.RULE_NAME, R.RISK_DOMAIN,
        A.RISK_SCORE, A.SEVERITY, A.EXPLANATION, A.ALERT_STATUS
    FROM RISK.ALERTS A JOIN RISK.RISK_RULES R ON A.RULE_ID = R.RULE_ID AND A.RULE_VERSION = R.RULE_VERSION
    WHERE A.ALERT_STATUS = ''NEW'' ORDER BY A.RISK_SCORE DESC LIMIT 20'
UNION ALL SELECT 'QT_003', 'RAPID_MOVEMENT',
    'rapid,movement,funds,transfer,24 hours,counterpart',
    'Show accounts with rapid fund movement patterns',
    'SELECT A.ALERT_ID, A.ACCOUNT_ID, A.CUSTOMER_ID, A.RISK_SCORE, A.EXPLANATION, A.ALERT_STATUS
    FROM RISK.ALERTS A WHERE A.RULE_ID = ''AML_002'' ORDER BY A.RISK_SCORE DESC'
UNION ALL SELECT 'QT_004', 'LIQUIDITY_DECLINE',
    'liquidity,decline,balance,material,seven,7 day',
    'Show material liquidity declines over balance dates',
    'SELECT ACCOUNT_ID, BALANCE_DATE, CLOSING_BALANCE, AVAILABLE_LIQUIDITY, PCT_CHANGE_7D, BALANCE_7D_AGO
    FROM RISK.V_FEAT_LIQUIDITY_DECLINE WHERE PCT_CHANGE_7D < -50
    ORDER BY PCT_CHANGE_7D ASC LIMIT 20'
UNION ALL SELECT 'QT_005', 'CASE_EVIDENCE',
    'evidence,missing,case,finding,submit,review',
    'Check evidence status for a case',
    'SELECT C.CASE_ID, C.CASE_STATUS, C.ALERT_ID, CE.EVIDENCE_ID, AE.EVIDENCE_TYPE, AE.SOURCE_OBJECT
    FROM CASE_MGMT.CASES C
    LEFT JOIN CASE_MGMT.CASE_EVIDENCE CE ON C.CASE_ID = CE.CASE_ID
    LEFT JOIN RISK.ALERT_EVIDENCE AE ON CE.EVIDENCE_ID = AE.EVIDENCE_ID
    WHERE C.CASE_ID = :PARAM1'
UNION ALL SELECT 'QT_006', 'DRAFT_FINDING',
    'draft,finding,create,generate,narrative',
    'Retrieve data for draft finding generation',
    'SELECT C.CASE_ID, A.ALERT_ID, A.RULE_ID, R.RULE_NAME, A.RISK_SCORE, A.EXPLANATION,
        AE.EVIDENCE_ID, AE.EVIDENCE_TYPE, AE.SOURCE_OBJECT, AE.SOURCE_RECORD_ID
    FROM CASE_MGMT.CASES C
    JOIN RISK.ALERTS A ON C.ALERT_ID = A.ALERT_ID
    JOIN RISK.RISK_RULES R ON A.RULE_ID = R.RULE_ID AND A.RULE_VERSION = R.RULE_VERSION
    LEFT JOIN CASE_MGMT.CASE_EVIDENCE CE ON C.CASE_ID = CE.CASE_ID
    LEFT JOIN RISK.ALERT_EVIDENCE AE ON CE.EVIDENCE_ID = AE.EVIDENCE_ID
    WHERE C.CASE_ID = :PARAM1'
UNION ALL SELECT 'QT_007', 'INVESTIGATION_REPORT',
    'report,investigation,generate,audit,lineage',
    'Generate investigation report data for a case',
    'SELECT C.CASE_ID, C.CASE_STATUS, C.CREATED_BY, C.CREATED_AT,
        F.FINDING_ID, F.FINDING_VERSION, F.FINDING_STATUS, F.NARRATIVE, F.POLICY_CITATIONS_JSON,
        A.ALERT_ID, A.RULE_ID, A.RISK_SCORE, A.SEVERITY, A.EXPLANATION
    FROM CASE_MGMT.CASES C
    JOIN RISK.ALERTS A ON C.ALERT_ID = A.ALERT_ID
    LEFT JOIN CASE_MGMT.FINDINGS F ON C.CASE_ID = F.CASE_ID
    WHERE C.CASE_ID = :PARAM1
    ORDER BY F.FINDING_VERSION DESC'
UNION ALL SELECT 'QT_008', 'STRUCTURING',
    'structuring,below,threshold,repeated,structure',
    'Show structuring detection alerts',
    'SELECT A.ALERT_ID, A.ACCOUNT_ID, A.CUSTOMER_ID, A.RISK_SCORE, A.EXPLANATION
    FROM RISK.ALERTS A WHERE A.RULE_ID = ''AML_001'' ORDER BY A.RISK_SCORE DESC';

GRANT SELECT ON APP.QUERY_TEMPLATES TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON APP.QUERY_TEMPLATES TO ROLE REGINTEL_ANALYST;
