-- ============================================================================
-- RegIntel Copilot: 10_case_management.sql
-- Case lifecycle procedures and workflow enforcement.
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- Procedure: Open a case from an alert
CREATE OR REPLACE PROCEDURE CASE_MGMT.OPEN_CASE(
    P_CASE_ID VARCHAR, P_ALERT_ID VARCHAR, P_CREATED_BY VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL AS
$$
BEGIN
    -- Verify alert exists
    IF (NOT EXISTS (SELECT 1 FROM RISK.ALERTS WHERE ALERT_ID = :P_ALERT_ID)) THEN
        RETURN 'ERROR: Alert ' || :P_ALERT_ID || ' not found';
    END IF;
    -- Check no duplicate case for this alert
    IF (EXISTS (SELECT 1 FROM CASE_MGMT.CASES WHERE ALERT_ID = :P_ALERT_ID)) THEN
        RETURN 'ERROR: Case already exists for alert ' || :P_ALERT_ID;
    END IF;

    INSERT INTO CASE_MGMT.CASES (CASE_ID, ALERT_ID, CASE_STATUS, ASSIGNED_ROLE, CREATED_BY)
    VALUES (:P_CASE_ID, :P_ALERT_ID, 'NEW', 'REGINTEL_ANALYST', :P_CREATED_BY);

    -- Attach all evidence from the alert to the case
    INSERT INTO CASE_MGMT.CASE_EVIDENCE (CASE_ID, EVIDENCE_ID, ATTACHED_BY)
    SELECT :P_CASE_ID, EVIDENCE_ID, :P_CREATED_BY
    FROM RISK.ALERT_EVIDENCE WHERE ALERT_ID = :P_ALERT_ID;

    -- Update alert status
    UPDATE RISK.ALERTS SET ALERT_STATUS = 'UNDER_REVIEW' WHERE ALERT_ID = :P_ALERT_ID;

    -- Log the action
    INSERT INTO AUDIT.ACTIVITY_LOG (ACTIVITY_ID, USER_NAME, ACTIVE_ROLE, ACTION_TYPE, OBJECT_TYPE, OBJECT_ID, REQUEST_TEXT, STATUS)
    VALUES (UUID_STRING(), :P_CREATED_BY, 'REGINTEL_ANALYST', 'OPEN_CASE', 'CASE', :P_CASE_ID, 'Opened case for alert ' || :P_ALERT_ID, 'SUCCESS');

    RETURN 'Case ' || :P_CASE_ID || ' opened successfully for alert ' || :P_ALERT_ID;
END
$$;

-- Procedure: Update case status with transition validation
CREATE OR REPLACE PROCEDURE CASE_MGMT.UPDATE_CASE_STATUS(
    P_CASE_ID VARCHAR, P_NEW_STATUS VARCHAR, P_USER VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL AS
$$
DECLARE
    v_current_status VARCHAR;
BEGIN
    SELECT CASE_STATUS INTO :v_current_status FROM CASE_MGMT.CASES WHERE CASE_ID = :P_CASE_ID;
    IF (:v_current_status IS NULL) THEN
        RETURN 'ERROR: Case ' || :P_CASE_ID || ' not found';
    END IF;

    -- Validate state transitions
    IF (:v_current_status = 'NEW' AND :P_NEW_STATUS NOT IN ('INVESTIGATING')) THEN
        RETURN 'ERROR: Invalid transition from NEW to ' || :P_NEW_STATUS;
    ELSEIF (:v_current_status = 'INVESTIGATING' AND :P_NEW_STATUS NOT IN ('DRAFT_FINDING', 'CLOSED')) THEN
        RETURN 'ERROR: Invalid transition from INVESTIGATING to ' || :P_NEW_STATUS;
    ELSEIF (:v_current_status = 'DRAFT_FINDING' AND :P_NEW_STATUS NOT IN ('REVIEW_REQUIRED')) THEN
        RETURN 'ERROR: Invalid transition from DRAFT_FINDING to ' || :P_NEW_STATUS;
    ELSEIF (:v_current_status = 'REVIEW_REQUIRED' AND :P_NEW_STATUS NOT IN ('APPROVED', 'REJECTED')) THEN
        RETURN 'ERROR: Invalid transition from REVIEW_REQUIRED to ' || :P_NEW_STATUS;
    ELSEIF (:v_current_status = 'REJECTED' AND :P_NEW_STATUS NOT IN ('INVESTIGATING')) THEN
        RETURN 'ERROR: Invalid transition from REJECTED to ' || :P_NEW_STATUS;
    ELSEIF (:v_current_status IN ('APPROVED', 'CLOSED')) THEN
        RETURN 'ERROR: Case is already in terminal state ' || :v_current_status;
    END IF;

    UPDATE CASE_MGMT.CASES SET CASE_STATUS = :P_NEW_STATUS WHERE CASE_ID = :P_CASE_ID;

    INSERT INTO AUDIT.ACTIVITY_LOG (ACTIVITY_ID, USER_NAME, ACTION_TYPE, OBJECT_TYPE, OBJECT_ID, REQUEST_TEXT, STATUS)
    VALUES (UUID_STRING(), :P_USER, 'STATUS_CHANGE', 'CASE', :P_CASE_ID,
        'Status: ' || :v_current_status || ' -> ' || :P_NEW_STATUS, 'SUCCESS');

    RETURN 'Case ' || :P_CASE_ID || ' updated: ' || :v_current_status || ' -> ' || :P_NEW_STATUS;
END
$$;

-- Procedure: Create a draft finding
CREATE OR REPLACE PROCEDURE CASE_MGMT.CREATE_FINDING(
    P_CASE_ID VARCHAR, P_NARRATIVE VARCHAR, P_POLICY_CITATIONS VARIANT, P_CREATED_BY VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL AS
$$
DECLARE
    v_finding_id VARCHAR;
    v_version INTEGER;
    v_evidence VARIANT;
BEGIN
    IF (NOT EXISTS (SELECT 1 FROM CASE_MGMT.CASES WHERE CASE_ID = :P_CASE_ID)) THEN
        RETURN 'ERROR: Case ' || :P_CASE_ID || ' not found';
    END IF;

    -- Get next version
    SELECT COALESCE(MAX(FINDING_VERSION), 0) + 1 INTO :v_version
    FROM CASE_MGMT.FINDINGS WHERE CASE_ID = :P_CASE_ID;

    LET v_finding_id := 'FND_' || :P_CASE_ID || '_V' || :v_version::VARCHAR;

    -- Collect evidence snapshot
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT('evidence_id', CE.EVIDENCE_ID, 'type', AE.EVIDENCE_TYPE, 'source', AE.SOURCE_OBJECT))
    INTO :v_evidence
    FROM CASE_MGMT.CASE_EVIDENCE CE
    JOIN RISK.ALERT_EVIDENCE AE ON CE.EVIDENCE_ID = AE.EVIDENCE_ID
    WHERE CE.CASE_ID = :P_CASE_ID;

    INSERT INTO CASE_MGMT.FINDINGS (FINDING_ID, CASE_ID, FINDING_VERSION, FINDING_STATUS,
        NARRATIVE, SUPPORTING_EVIDENCE_JSON, POLICY_CITATIONS_JSON, CREATED_BY)
    VALUES (:v_finding_id, :P_CASE_ID, :v_version, 'DRAFT',
        :P_NARRATIVE, :v_evidence, :P_POLICY_CITATIONS, :P_CREATED_BY);

    -- Update case status
    UPDATE CASE_MGMT.CASES SET CASE_STATUS = 'DRAFT_FINDING' WHERE CASE_ID = :P_CASE_ID;

    INSERT INTO AUDIT.ACTIVITY_LOG (ACTIVITY_ID, USER_NAME, ACTION_TYPE, OBJECT_TYPE, OBJECT_ID, REQUEST_TEXT, STATUS)
    VALUES (UUID_STRING(), :P_CREATED_BY, 'CREATE_FINDING', 'FINDING', :v_finding_id,
        'Created draft finding v' || :v_version || ' for case ' || :P_CASE_ID, 'SUCCESS');

    RETURN 'Draft finding ' || :v_finding_id || ' created for case ' || :P_CASE_ID;
END
$$;

-- Procedure: Approve or reject a finding (compliance reviewer only)
CREATE OR REPLACE PROCEDURE CASE_MGMT.REVIEW_FINDING(
    P_CASE_ID VARCHAR, P_DISPOSITION VARCHAR, P_REVIEWER VARCHAR, P_COMMENTS VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL AS
$$
DECLARE
    v_finding_id VARCHAR;
    v_version INTEGER;
BEGIN
    IF (:P_DISPOSITION NOT IN ('APPROVED', 'REJECTED')) THEN
        RETURN 'ERROR: Disposition must be APPROVED or REJECTED';
    END IF;

    -- Get latest finding
    SELECT FINDING_ID, FINDING_VERSION INTO :v_finding_id, :v_version
    FROM CASE_MGMT.FINDINGS WHERE CASE_ID = :P_CASE_ID AND FINDING_STATUS = 'DRAFT'
    ORDER BY FINDING_VERSION DESC LIMIT 1;

    IF (:v_finding_id IS NULL) THEN
        RETURN 'ERROR: No draft finding for case ' || :P_CASE_ID;
    END IF;

    UPDATE CASE_MGMT.FINDINGS
    SET FINDING_STATUS = :P_DISPOSITION, APPROVED_BY = :P_REVIEWER, APPROVED_AT = CURRENT_TIMESTAMP()
    WHERE FINDING_ID = :v_finding_id AND FINDING_VERSION = :v_version;

    UPDATE CASE_MGMT.CASES
    SET CASE_STATUS = :P_DISPOSITION, REVIEWED_BY = :P_REVIEWER, REVIEWED_AT = CURRENT_TIMESTAMP(),
        DISPOSITION = :P_DISPOSITION, REVIEWER_COMMENTS = :P_COMMENTS
    WHERE CASE_ID = :P_CASE_ID;

    INSERT INTO AUDIT.ACTIVITY_LOG (ACTIVITY_ID, USER_NAME, ACTION_TYPE, OBJECT_TYPE, OBJECT_ID, REQUEST_TEXT, STATUS)
    VALUES (UUID_STRING(), :P_REVIEWER, 'REVIEW_FINDING', 'FINDING', :v_finding_id,
        :P_DISPOSITION || ': ' || :P_COMMENTS, 'SUCCESS');

    RETURN 'Finding ' || :v_finding_id || ' ' || :P_DISPOSITION || ' by ' || :P_REVIEWER;
END
$$;

-- Case views
CREATE OR REPLACE VIEW CASE_MGMT.V_OPEN_CASES AS
SELECT C.*, A.RULE_ID, A.RISK_SCORE, A.SEVERITY, A.EXPLANATION
FROM CASE_MGMT.CASES C JOIN RISK.ALERTS A ON C.ALERT_ID = A.ALERT_ID
WHERE C.CASE_STATUS NOT IN ('APPROVED', 'CLOSED');

CREATE OR REPLACE VIEW CASE_MGMT.V_CASES_AWAITING_REVIEW AS
SELECT C.*, A.RULE_ID, A.RISK_SCORE, A.SEVERITY
FROM CASE_MGMT.CASES C JOIN RISK.ALERTS A ON C.ALERT_ID = A.ALERT_ID
WHERE C.CASE_STATUS = 'REVIEW_REQUIRED';

CREATE OR REPLACE VIEW CASE_MGMT.V_CASE_TIMELINE AS
SELECT OBJECT_ID AS CASE_ID, EVENT_TIMESTAMP, USER_NAME, ACTION_TYPE, REQUEST_TEXT, STATUS
FROM AUDIT.ACTIVITY_LOG WHERE OBJECT_TYPE IN ('CASE', 'FINDING')
ORDER BY EVENT_TIMESTAMP;

-- Grant permissions
GRANT SELECT ON ALL VIEWS IN SCHEMA CASE_MGMT TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA CASE_MGMT TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA CASE_MGMT TO ROLE REGINTEL_APP_ROLE;

GRANT USAGE ON PROCEDURE CASE_MGMT.OPEN_CASE(VARCHAR,VARCHAR,VARCHAR) TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON PROCEDURE CASE_MGMT.OPEN_CASE(VARCHAR,VARCHAR,VARCHAR) TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON PROCEDURE CASE_MGMT.UPDATE_CASE_STATUS(VARCHAR,VARCHAR,VARCHAR) TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON PROCEDURE CASE_MGMT.UPDATE_CASE_STATUS(VARCHAR,VARCHAR,VARCHAR) TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON PROCEDURE CASE_MGMT.CREATE_FINDING(VARCHAR,VARCHAR,VARIANT,VARCHAR) TO ROLE REGINTEL_APP_ROLE;
GRANT USAGE ON PROCEDURE CASE_MGMT.CREATE_FINDING(VARCHAR,VARCHAR,VARIANT,VARCHAR) TO ROLE REGINTEL_ANALYST;
GRANT USAGE ON PROCEDURE CASE_MGMT.REVIEW_FINDING(VARCHAR,VARCHAR,VARCHAR,VARCHAR) TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT USAGE ON PROCEDURE CASE_MGMT.REVIEW_FINDING(VARCHAR,VARCHAR,VARCHAR,VARCHAR) TO ROLE REGINTEL_APP_ROLE;
