-- ============================================================================
-- RegIntel Copilot: 11_audit_logging.sql
-- Audit trail views and logging infrastructure.
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- Main audit trail view
CREATE OR REPLACE VIEW AUDIT.V_AUDIT_TRAIL AS
SELECT
    ACTIVITY_ID, EVENT_TIMESTAMP, USER_NAME, ACTIVE_ROLE,
    ACTION_TYPE, OBJECT_TYPE, OBJECT_ID,
    REQUEST_TEXT, RESPONSE_SUMMARY, QUERY_ID, STATUS, ERROR_MESSAGE
FROM AUDIT.ACTIVITY_LOG
ORDER BY EVENT_TIMESTAMP DESC;

-- Audit summary by action type
CREATE OR REPLACE VIEW AUDIT.V_AUDIT_SUMMARY AS
SELECT
    DATE_TRUNC('day', EVENT_TIMESTAMP) AS AUDIT_DATE,
    ACTION_TYPE, STATUS, COUNT(*) AS EVENT_COUNT
FROM AUDIT.ACTIVITY_LOG
GROUP BY 1, 2, 3
ORDER BY 1 DESC, 4 DESC;

GRANT SELECT ON ALL VIEWS IN SCHEMA AUDIT TO ROLE REGINTEL_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA AUDIT TO ROLE REGINTEL_COMPLIANCE_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA AUDIT TO ROLE REGINTEL_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AUDIT TO ROLE REGINTEL_APP_ROLE;
