-- ============================================================================
-- RegIntel Copilot: 12_demo_queries.sql
-- All 8 demo questions as executable SQL.
-- ============================================================================

USE ROLE REGINTEL_ADMIN;
USE DATABASE REGINTEL;
USE WAREHOUSE COMPUTE_WH;

-- Q1: Which open alerts have the highest explainable risk score?
SELECT A.ALERT_ID, A.ACCOUNT_ID, A.CUSTOMER_ID, A.RULE_ID, R.RULE_NAME, R.RISK_DOMAIN,
    A.RISK_SCORE, A.SEVERITY, A.EXPLANATION, A.ALERT_STATUS
FROM RISK.ALERTS A
JOIN RISK.RISK_RULES R ON A.RULE_ID = R.RULE_ID AND A.RULE_VERSION = R.RULE_VERSION
WHERE A.ALERT_STATUS = 'NEW'
ORDER BY A.RISK_SCORE DESC
LIMIT 20;

-- Q2: Why was account A000123 flagged?
SELECT A.ALERT_ID, A.RULE_ID, R.RULE_NAME, R.RISK_DOMAIN, A.RISK_SCORE, A.SEVERITY,
    A.EXPLANATION, R.THRESHOLD_CONFIG, A.PRIMARY_TRANSACTION_ID
FROM RISK.ALERTS A
JOIN RISK.RISK_RULES R ON A.RULE_ID = R.RULE_ID AND A.RULE_VERSION = R.RULE_VERSION
WHERE A.ACCOUNT_ID = 'A000123'
ORDER BY A.RISK_SCORE DESC;

-- Q3: Accounts that received funds from 3+ counterparties and moved most out within 24h
SELECT M.ACCOUNT_ID, M.UNIQUE_CREDIT_SOURCES_24H, M.TOTAL_CREDITS_24H,
    M.TOTAL_DEBITS_24H, M.PCT_MOVED_OUT, M.WINDOW_START, M.WINDOW_END
FROM RISK.V_FEAT_MULE_BEHAVIOR M
WHERE M.PCT_MOVED_OUT >= 70
ORDER BY M.PCT_MOVED_OUT DESC;

-- Q4: Rapid movement alerts with policy evidence
SELECT A.ALERT_ID, A.ACCOUNT_ID, A.RISK_SCORE, A.EXPLANATION, A.ALERT_STATUS,
    PC.POLICY_ID, PC.SECTION_ID, PC.PARAGRAPH_ID, PC.CHUNK_TEXT AS POLICY_EXCERPT
FROM RISK.ALERTS A
CROSS JOIN POLICY.POLICY_CHUNKS PC
WHERE A.RULE_ID = 'AML_002'
AND (PC.SECTION_ID LIKE 'S3.2%' AND PC.POLICY_ID = 'POL-AML-001')
ORDER BY A.RISK_SCORE DESC;

-- Q5: Material liquidity declines over last seven balance dates
SELECT ACCOUNT_ID, BALANCE_DATE, CLOSING_BALANCE, BALANCE_7D_AGO, PCT_CHANGE_7D, AVAILABLE_LIQUIDITY
FROM RISK.V_FEAT_LIQUIDITY_DECLINE
WHERE ACCOUNT_ID = 'A000123' AND PCT_CHANGE_7D IS NOT NULL
ORDER BY BALANCE_DATE DESC
LIMIT 10;

-- Q6: Draft finding for case C000017 (data retrieval)
SELECT C.CASE_ID, C.CASE_STATUS, F.FINDING_ID, F.FINDING_VERSION, F.FINDING_STATUS,
    F.NARRATIVE, F.SUPPORTING_EVIDENCE_JSON, F.POLICY_CITATIONS_JSON,
    A.RULE_ID, A.RISK_SCORE, A.EXPLANATION
FROM CASE_MGMT.CASES C
JOIN RISK.ALERTS A ON C.ALERT_ID = A.ALERT_ID
LEFT JOIN CASE_MGMT.FINDINGS F ON C.CASE_ID = F.CASE_ID
WHERE C.CASE_ID = 'C000017';

-- Q7: Missing evidence before case C000017 can be submitted
SELECT C.CASE_ID, C.CASE_STATUS,
    CASE WHEN CE_COUNT > 0 THEN 'YES' ELSE 'MISSING' END AS HAS_TRANSACTION_EVIDENCE,
    CASE WHEN F.FINDING_ID IS NOT NULL THEN 'YES' ELSE 'MISSING' END AS HAS_FINDING,
    CASE WHEN F.POLICY_CITATIONS_JSON IS NOT NULL THEN 'YES' ELSE 'MISSING' END AS HAS_POLICY_CITATIONS,
    CASE WHEN C.CASE_STATUS = 'REVIEW_REQUIRED' THEN 'READY' ELSE 'NOT READY - Status: ' || C.CASE_STATUS END AS SUBMISSION_STATUS
FROM CASE_MGMT.CASES C
LEFT JOIN (SELECT CASE_ID, COUNT(*) AS CE_COUNT FROM CASE_MGMT.CASE_EVIDENCE GROUP BY CASE_ID) CE ON C.CASE_ID = CE.CASE_ID
LEFT JOIN CASE_MGMT.FINDINGS F ON C.CASE_ID = F.CASE_ID
WHERE C.CASE_ID = 'C000017';

-- Q8: Investigation report for case C000017
SELECT
    'REGINTEL COPILOT INVESTIGATION REPORT' AS REPORT_TITLE,
    C.CASE_ID, C.CASE_STATUS, C.CREATED_BY, C.CREATED_AT,
    A.ALERT_ID, A.RULE_ID, R.RULE_NAME, A.RISK_SCORE, A.SEVERITY, A.EXPLANATION,
    F.FINDING_ID, F.FINDING_VERSION, F.FINDING_STATUS, F.NARRATIVE,
    F.SUPPORTING_EVIDENCE_JSON, F.POLICY_CITATIONS_JSON,
    F.CREATED_BY AS FINDING_AUTHOR, F.APPROVED_BY, F.APPROVED_AT
FROM CASE_MGMT.CASES C
JOIN RISK.ALERTS A ON C.ALERT_ID = A.ALERT_ID
JOIN RISK.RISK_RULES R ON A.RULE_ID = R.RULE_ID AND A.RULE_VERSION = R.RULE_VERSION
LEFT JOIN CASE_MGMT.FINDINGS F ON C.CASE_ID = F.CASE_ID
WHERE C.CASE_ID = 'C000017'
ORDER BY F.FINDING_VERSION DESC;
